asseci/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from asseci import views
from . import views
from .views import EvenementListView, EvenementDetailView, AnnonceListView, AnnonceDetailView, ForumListView


from accounts import views as accounts_views

from django.contrib.auth import views as auth_views

app_name = 'asseci'



urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^$', views.accueil, name='accueil'),
    url(r'^presentation/$', views.presentation, name='presentation'),
    url(r'^presentation/le-bureau/$', views.bureau, name='bureau'),
    url(r'^presentation/nos-missions/$', views.missions, name='missions'),
    url(r'^promotion/id/$', views.membre, name='membre'),
    url(r'^promotion/id/2/$', views.membre2, name='membre2'),
    url(r'^promotion/membre/id/profil/$', views.membreId, name='membreId'),
    url(r'^actualites/evenement_list/$', EvenementListView.as_view(), name='evenement-list'),
    url(r'^actualites/evenement/(?P<pk>\d+)/$', EvenementDetailView.as_view(), name='evenement-detail'),
    url(r'^actualites/annonce_list/$', AnnonceListView.as_view(), name='annonce-list'),
    url(r'^actualites/annonce/(?P<pk>\d+)/$', AnnonceDetailView.as_view(), name='annonce-detail'),
    url(r'^actualites/timeline/$', views.timeline, name='timeline'),
    url(r'^mentions-legales/$', views.mentionslegales, name='mentionslegales'),
    url(r'^donation/$', views.paiement, name='paiement'),
    url(r'^plan-du-site/$', views.plan, name='plan'),
    url(r'^contact/$', views.contact, name='contact'),
    
    url(r'^tableau-de-bord/$', views.dashboard, name='dashboard'),
    url(r'^tableau-de-bord/infos-personnelles/$', accounts_views.UserUpdateView.as_view(), name='my_account'),
    url(r'^tableau-de-bord/changer-mot-de-passe/$', accounts_views.change_password, name='change_password'),

    url(r'^contacts/formulaire/$', views.ContactezNous, name='contacteznous'),

    url(r'^tableau-de-bord/infos-persos/(?P<pk>\d+)/$', views.infos_persos, name='infos-persos'),

    # FORUM
    #url(r'^forum/$', views.forum, name='forum'),
    url(r'^forum/themes/$', views.ForumListView.as_view(), name='forum'),
    url(r'^forum/themes/ajouter-theme/$', views.ForumCreateView.as_view(), name='forum_create'),



    url(r'^inscription/$', accounts_views.signup, name='signup'),

    
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='asseci/login.html'), name='login'),
    #url(r'^themes/(?P<pk>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^themes/(?P<pk>\d+)/nouveau/$', views.new_topic, name='new_topic'),
    url(r'^themes/(?P<pk>\d+)/sujets/(?P<topic_pk>\d+)/$', views.topic_posts, name='topic_posts'),
    url(r'^themes/(?P<pk>\d+)/sujets/(?P<topic_pk>\d+)/repondre/$', views.reply_topic, name='reply_topic'),
    url(r'^nouveau_post/$', views.NewPostView.as_view(), name='new_post'),
    url(r'^themes/(?P<pk>\d+)/sujets/(?P<topic_pk>\d+)/commentaires/(?P<post_pk>\d+)/editer/$',
        views.PostUpdateView.as_view(), name='edit_post'),
    url(r'^themes/(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board_topics'),
    url(r'^themes/(?P<pk>\d+)/sujets/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='topic_posts'),


    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='asseci/password_change.html'),
    name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='asseci/password_change_done.html'),
        name='password_change_done'),

    url(r'^reset/$',
    auth_views.PasswordResetView.as_view(
        template_name='asseci/password_reset.html',
        email_template_name='asseci/password_reset_email.html',
        subject_template_name='asseci/password_reset_subject.txt'
    ),
    name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='asseci/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='asseci/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='asseci/password_reset_complete.html'),
        name='password_reset_complete'),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from asseci import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^asseci/', include('asseci.urls', namespace='asseci')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

asseci/forms.py
from django import forms
from .models import Evenement
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import StrictButton
from crispy_forms.layout import Layout
from crispy_forms.bootstrap import TabHolder, Tab
from django.contrib.auth.models import User

from .models import Evenement, Post, ContactezNous, Board



#  your forms.



class EvenementForm(forms.ModelForm):

    class Meta:
        model = Evenement
        fields = ['evenement', 'lieu', 'dateCreation', 'jour', 'heure', 'hDebut', 'hFin', 
        'contact', 'nbreParticipants', 'bureau', 'odd1', 'odd2', 'odd3', 'odd4', 'odd5', 
        'odd6', 'odd7', 'odd8', 'odd9', 'odd10' ]

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['name', 'description' ]

class ContactezNousForm(forms.ModelForm):
    class Meta:
        model = ContactezNous
        fields = ['civilite', 'vousetes', 'nom', 'email', 'phone', 'message', ]

asseci/views.py
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.views.decorators.csrf import csrf_exempt

from django.http import HttpResponse

from django.views import generic
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from django.db.models import Count

from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.utils import timezone

#from django.contrib.auth.decorators import login_required
#from django.utils.decorators import method_decorator

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.forms import ModelForm
#from .forms import EvenementForm
import re
from django.db.models import Q
from django.template.loader import render_to_string

from .models import Evenement, Annonce, ThemeForum, Board, Topic, Post, ContactezNous

from django.contrib.auth.models import User
from .forms import PostForm, ContactezNousForm, BoardForm

from django.contrib import messages

# Create your views here.


# Accueil
def accueil(request):
	events = Evenement.objects.all().order_by('evenement')[:2]
	success_url = reverse_lazy('asseci:evenement_detail')
	return render(request, 'asseci/accueil.html', {'events': events})

# Presentation
def presentation(request):
    return render(request, 'asseci/presentation.html', {})

# Presentation / Mission
def missions(request):
	return render(request, 'asseci/missions.html', {})

# Presentation / Bureau
def bureau(request):
	return render(request, 'asseci/bureau.html', {})

# Profils & Membres
def membre(request):
	return render(request, 'asseci/membre.html', {})

# Profils & Membres
def membre2(request):
	return render(request, 'asseci/membre2.html', {})

def infos_persos(request, pk):
    infos = get_object_or_404(User, pk=pk)
    return render(request, 'asseci/infos_persos.html', {'infos': infos,})


# Profils & Membres / Id
def membreId(request):
	return render(request, 'asseci/membreId.html', {})

# Mentions Légales
def mentionslegales(request):
	return render(request, 'asseci/mentionslegales.html', {})

# Paiement
def paiement(request):
	return render(request, 'asseci/paiement.html', {})

# Plan du Site
def plan(request):
	return render(request, 'asseci/plan.html', {})

# Contact
def contact(request):
	return render(request, 'asseci/contact.html', {})

# Tableau de Bord
def dashboard(request):
    return render(request, 'asseci/dashboard.html', {})

# ContactezNous
def ContactezNous(request):
    if request.method == 'POST':
        form = ContactezNousForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Votre requête a été transmis avec succes, merci de nous avoir contacter, une réponse vous sera envoyer par courriel.')
            return redirect('asseci:contacteznous')
    else:
        form = ContactezNousForm()
    return render(request, 'asseci/contacteznous.html', {'form': form, })



# Evenements
class EvenementListView(ListView):

    model = Evenement
    template_name = 'asseci/evenement_list.html'
    context_object_name = 'object_list'
    paginate_by = 5
    queryset = Evenement.objects.all()

    #evenement_list = Evenement.objects.all()
    #paginator = Paginator(evenement_list, 1)

    #def get_context_data(self, **kwargs):
        #context = super(EvenementListView, self).get_context_data(**kwargs)
        #return context

# Evenement DetailView
class EvenementDetailView(DetailView):

    model = Evenement

    def get_context_data(self, **kwargs):
        context = super(EvenementDetailView, self).get_context_data(**kwargs)
        success_url = reverse_lazy('asseci:evenement_list')
        return context

# Annonce List View
class AnnonceListView(ListView):

	model = Annonce
	template_name = 'asseci/annonce_list.html'
	context_object_name = 'object_list'
	paginate_by = 5
	queryset = Annonce.objects.all()


    #model = Annonce

    #def get_context_data(self, **kwargs):
        #context = super(AnnonceListView, self).get_context_data(**kwargs)
        #return context

# Annonce DetailView
class AnnonceDetailView(DetailView):

    model = Annonce

    def get_context_data(self, **kwargs):
        context = super(AnnonceDetailView, self).get_context_data(**kwargs)
        success_url = reverse_lazy('asseci:annonce_list')
        return context

# Actualités / Timeline
def timeline(request):
	evenement = Evenement.objects.all()
	annonces = Annonce.objects.all()
	return render(request, 'asseci/timeline.html', {'evenement' : evenement, 'annonces' : annonces,  })


# FORUM
def forum(request):
    boards = Board.objects.all()
    return render(request, 'asseci/forum.html', {'boards': boards})

# FORUM List View
class ForumListView(ListView):

	model = Board
	template_name = 'asseci/forum.html'
	context_object_name = 'boards'
	paginate_by = 5
	queryset = Board.objects.all()

# FORUM Create View
class ForumCreateView(CreateView):
    model = Board
    form_class = BoardForm
    success_url = reverse_lazy('asseci:forum')
    template_name = 'asseci/new_board.html'




def board_topics(request, pk):
    board = get_object_or_404(Board, pk=pk)
    queryset = board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
    page = request.GET.get('page', 1)

    paginator = Paginator(queryset, 20)

    try:
        topics = paginator.page(page)
    except PageNotAnInteger:
        # fallback to the first page
        topics = paginator.page(1)
    except EmptyPage:
        # probably the user tried to add a page number
        # in the url, so we fallback to the last page
        topics = paginator.page(paginator.num_pages)

    return render(request, 'asseci/topics.html', {'board': board, 'topics': topics})

def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)

    if request.method == 'POST':
        subject = request.POST['subject']
        message = request.POST['message']

        user = User.objects.first()  # TODO: get the currently logged in user

        topic = Topic.objects.create(
            subject=subject,
            board=board,
            starter=request.user
        )

        post = Post.objects.create(
            message=message,
            topic=topic,
            created_by=request.user
        )

        return redirect('asseci:topic_posts', pk=pk, topic_pk=topic.pk)  # <- here

    return render(request, 'asseci/new_topic.html', {'board': board})



def topic_posts(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    topic.views += 1
    topic.save()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()
            return redirect('asseci:topic_posts', pk=pk, topic_pk=topic_pk)
        else:
            form = PostForm() 
    return render(request, 'asseci/topic_posts.html', {'topic': topic})

def reply_topic(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()
            return redirect('asseci:topic_posts', pk=pk, topic_pk=topic_pk)
    else:
        form = PostForm()
    return render(request, 'asseci/reply_topic.html', {'topic': topic, 'form': form})

class NewPostView(CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('asseci:post_list')
    template_name = 'asseci/new_post.html'

#@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    fields = ('message', )
    template_name = 'asseci/edit_post.html'
    pk_url_kwarg = 'post_pk'
    context_object_name = 'post'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.updated_by = self.request.user
        post.updated_at = timezone.now()
        post.save()
        return redirect('asseci:topic_posts', pk=post.topic.board.pk, topic_pk=post.topic.pk)

class TopicListView(ListView):
    model = Topic
    context_object_name = 'topics'
    template_name = 'asseci/topics.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        kwargs['board'] = self.board
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.board = get_object_or_404(Board, pk=self.kwargs.get('pk'))
        queryset = self.board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
        return queryset

class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'asseci/topic_posts.html'
    paginate_by = 2

    def get_context_data(self, **kwargs):
        self.topic.views += 1
        self.topic.save()
        kwargs['topic'] = self.topic
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.topic = get_object_or_404(Topic, board__pk=self.kwargs.get('pk'), pk=self.kwargs.get('topic_pk'))
        queryset = self.topic.posts.order_by('created_at')
        return queryset

asseci/templates/asseci/annonce_list.html
{% extends 'asseci/base.html' %}


{% block title %}ANNONCES{% endblock %}

{% block vtitle %}ANNONCES{% endblock %}


{% block content %}

{% load staticfiles %}

  <!-- Start Content -->
  <!-- Start Content -->
  <div class="main" role="main">
    <div id="content" class="content full">
      <div class="container">
        <div class="row"><div class="col-md-9 contenu">
          

<!-- Events Listing -->
<div class="listing events-listing">
  
  <header class="listing-header">
    <h2>Nos annonces</h2>
  </header>
  
  <section class="listing-cont">
    <ul>
      
      {% for annonce in object_list %}
      <li class="item event-item">
     
        <div class="event-detail">
         <h4><a href="single-post.html">{{ annonce.titre }}</a></h4>
          <span class="event-dayntime meta-data">{{ annonce.annonce }}</span> 
          <span class="event-dayntime meta-data">{{ annonce.jour }} | {{ annonce.dateCreation }}</span> </div>
        <div class="to-event-url">
     <div><br /><br /><a href="{% url 'asseci:annonce-detail' annonce.id %}" class="btn btn-default btn-sm">+ d'infos</a></div> 
        </div>
      </li>
      {% endfor %}
      
      
    </ul>
  </section><br><br><br>

  <div class="row">
    <div class="col-md-6"></div>
    <div class="col-md-6">
      {% if is_paginated %}
      <nav aria-label="Evenement pagination" class="mb-4">
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li>
              <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            </li>
          {% else %}
            <li class="disabled">
              <span>&laquo;</span>
            </li>
          {% endif %}

          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="active">
                <span>
                  {{ i }}
                  <span class="sr-only">(current)</span>
                </span>
              </li>
            {% else %}
              <li>
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <li>
              <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            </li>
          {% else %}
            <li class="disabled">
              <span>&raquo;</span>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
    </div>
  </div>





</div>
<div class="spacer-30"></div>
<div class="spacer-30"></div>
</div>

          <!-- Start Sidebar -->
          <div class="col-md-3 sidebar">
            
<div class="widget sidebar-widget">
  
  <div class="sidebar-widget-title">
    <h3><i class="fa fa-gears"></i> &nbsp;Options</h3>
  </div>
  
  <ul>
    
      <li><i class="fa fa-search"></i> &nbsp;&nbsp;<a href="#" class="actif">Recherche</a></li>

      <li><i class="fa fa-send"></i> &nbsp;&nbsp;<a href="#" class="actif">Mes annonces</a></li>
      
      <li><i class="fa fa-edit"></i> &nbsp;&nbsp;<a href="#" class="">Publier</a></li>
      
      
  </ul>
</div>

          </div>
        </div>
      </div>
    </div>
  </div> 
  


<!-- Start Featured Gallery -->
  <div class="featured-gallery">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-3">
          <h4>Galerie</h4>
          <a href="timeline.html" class="btn btn-default btn-lg">Plus</a> </div>
        <div class="col-md-3 col-sm-3 post format-image"> <a href="{% static 'asseci/media/382/gallery-img6.jpg' %}" class="media-box" data-rel="prettyPhoto[Gallery]"> <img src="{% static 'asseci/media/382/gallery-img6.jpg' %}" alt=""> </a> </div>
        <div class="col-md-3 col-sm-3 post format-video"> <a href="{% static 'asseci/media/382/gallery-img3.jpg' %}" class="media-box" data-rel="prettyPhoto[Gallery]"> <img src="{% static 'asseci/media/382/gallery-img3.jpg' %}" alt=""> </a> </div>
        <div class="col-md-3 col-sm-3 post format-image"> <a href="{% static 'asseci/media/382/gallery-img4.jpg' %}" class="media-box" data-rel="prettyPhoto[Gallery]"> <img src="{% static 'asseci/media/382/gallery-img4.jpg' %}" alt=""> </a> </div>
      </div>
    </div>
  </div>
<!-- End Featured Gallery --> 



  {% endblock %}

asseci/templates/asseci/plan.html
{% extends 'asseci/base.html' %}


{% block title %}PLAN DU SITE{% endblock %}

{% block vtitle %}PLAN DU SITE{% endblock %}


{% block content %}

{% load staticfiles %}

  <!-- Start Content -->
  <div class="main" role="main">
    <div id="content" class="content full">
      <div class="container">
        <div class="row"><div class="col-md-12 contenu">
          

<article class="col-md-8">
  
  <h1>Menu principal</h1>
  
  <nav>
    <div class="widget sitemap">
    <ul class="sf-menu">
      <li> <a href="{% url 'asseci:accueil' %}">Accueil</a>
      <li  role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'asseci:presentation' %}" role="button" aria-haspopup="true" aria-expanded="false">
          Présentation &nbsp;|&nbsp; <a href="{% url 'asseci:missions' %}">Notre Mission</a> &nbsp;|&nbsp; <a href="{% url 'asseci:bureau' %}">Le Bureau</a> 
        </a>
        <ul class="dropdown-menu">
          <li class="link_1"> <a href="{% url 'asseci:missions' %}">Notre Mission</a>
          <li class="link_2"> <a href="{% url 'asseci:bureau' %}">Le Bureau</a>
        </ul>
      </li>
      <li> <a href="{% url 'asseci:membre' %}">Membres</a>
      <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'asseci:evenement-list' %}" role="button" aria-haspopup="true" aria-expanded="false">
          Actualites &nbsp;|&nbsp; <a href="{% url 'asseci:evenement-list' %}">Evènements</a> &nbsp;|&nbsp; <a href="{% url 'asseci:annonce-list' %}">Annonces</a> &nbsp;|&nbsp; <a href="{% url 'asseci:timeline' %}">Timeline</a>
        </a>
        <ul class="dropdown-menu">
          <li> <a href="{% url 'asseci:evenement-list' %}">Evènements</a>
          <li> <a href="{% url 'asseci:annonce-list' %}">Annonces</a>
          <li> <a href="{% url 'asseci:timeline' %}">Timeline</a>
        </ul>
      </li>
      <li role="presentation" class="dropdown"> 
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Education
        </a>
        <!--ul class="dropdown-menu">
          <li> <a href="single-post.html">Reseau</a>
          <li> <a href="single-post-2.html">Developpement</a>
          <li> <a href="single-post.html">Certifications</a>
          <li> <a href="single-post-2.html">Base de Données</a>
          <li> <a href="single-post.html">Systèmes</a>
          <li> <a href="single-post.html">Bureautique</a>
          <li> <a href="single-post.html">Gestion de Projet</a>
          <li> <a href="single-post.html">Insertion Professionnelle</a>
        </ul-->
      </li>
      <li role="presentation" class="dropdown"> 
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Espace Pro &nbsp;|&nbsp; <a href="#">Forum</a> &nbsp;|&nbsp; <a href="#">Mon Blog</a>
        </a>
        <ul class="dropdown-menu">
          <li> <a href="#">Forum</a>
          <li> <a href="#">Mon Blog</a>
          </li>
        </ul>
      </li>
      <li> <a href="#">Contact</a>

    </ul>
    </div>
  </nav>
</article>




<article class="col-md-4">
  
  <h1>Menu pied de page</h1>
  
  <nav>
    <div class="widget sitemap">
      
      <ul>
        
        
        <li class="link_1"> <a href="{% url 'asseci:mentionslegales' %}"  class="" target="_self">Informations légales</a>
          
          
          
        
        <li class="link_2"> <a href="{% url 'asseci:paiement' %}"  class="" target="_self">Sécurité des paiements</a>
          
          
          
        
        <li class="link_3"> <a href="{% url 'asseci:plan' %}"  class="actif" target="_self">Plan du site</a>
          
          
          
        </li>
      </ul>
      
    </div>
  </nav>
</article>


</div>
          
        </div>
      </div>
    </div>
  </div>
  


<!-- Start Featured Gallery -->
  <div class="featured-gallery">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-3">
          <h4>Galerie</h4>
          <a href="timeline.html" class="btn btn-default btn-lg">Plus</a> </div>
        <div class="col-md-3 col-sm-3 post format-image"> <a href="{% static 'asseci/media/382/gallery-img6.jpg' %}" class="media-box" data-rel="prettyPhoto[Gallery]"> <img src="{% static 'asseci/media/382/gallery-img6.jpg' %}" alt=""> </a> </div>
        <div class="col-md-3 col-sm-3 post format-video"> <a href="{% static 'asseci/media/382/gallery-img3.jpg' %}" class="media-box" data-rel="prettyPhoto[Gallery]"> <img src="{% static 'asseci/media/382/gallery-img3.jpg' %}" alt=""> </a> </div>
        <div class="col-md-3 col-sm-3 post format-image"> <a href="{% static 'asseci/media/382/gallery-img4.jpg' %}" class="media-box" data-rel="prettyPhoto[Gallery]"> <img src="{% static 'asseci/media/382/gallery-img4.jpg' %}" alt=""> </a> </div>
      </div>
    </div>
  </div>
<!-- End Featured Gallery --> 



  {% endblock %}